name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: |
        go build -v ./orch/orch.go
        go build -v ./regular/regular.go
        go build -v ./wordpress/wordpress.go

    - name: Test
      run: |
        go test -v ./orch/orch.go
        go test -v ./regular/regular.go
        go test -v ./wordpress/wordpress.go
